### PR TITLE
switch from travis to github actions

### PR DESCRIPTION
**Pull request by pawelmhm**

### CODE REVIEW

**Comment by Gallaecio** [comment]
You could also still use Tox, and run Tox from GitHub Actions, which is the approach we follow in Scrapy. The Scrapy GitHub Actions configuration is rather complex, but you could take inspiration from [Spidermon’s ](https://github.com/scrapinghub/spidermon/blob/master/.github/workflows/main.yml).

**Comment by pawelmhm** [comment]
@Gallaecio it's not that complex, I added it in scrapyrt, just need to fix test and it'll be fine.

**Comment by pawelmhm** [comment]
ok @Gallaecio I added actions next steps on the roadmap:

* making library compatible with python > 3.5. Currently it fails above 3.5
* related to that, switching to berkeleydb, as bsddb3 is deprecated and not recommended being used for python above 3.5 https://pypi.org/project/bsddb3/
* fixing warnings about deprecated Scrapy things, e.g. here: https://github.com/scrapy-plugins/scrapy-deltafetch/runs/2421289982?check_suite_focus=true

**Review by Gallaecio — APPROVED** [review]
I see you are still not using Tox, which I find confusing given the conversation in this issue (maybe a misunderstanding?). In any case, I have no strong opinion on that, using pytest directly works as well.

**Pull request merged**
